# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c813d26862b30ea39b3de16be89baf5156385d032c110e5b0bbee5c6cdfa893830ef3023de01fa98c696c2dfbc830f5e32d4f67a5f1e15b4ee7ce3337c96046

test:
  secret_key_base: 5bf85b718b1ec7a5dfcd78423b9d199fa71529c0343d15ee650881f922fe4acf3306d29fe9d9b79e8ab61dec90288b32f6265b2ddfb79ade89fd71d7f18d7543

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
